// <auto-generated />
namespace winform_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddHoaDon_SanPhamBan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHoaDon_SanPhamBan));
        
        string IMigrationMetadata.Id
        {
            get { return "202405110911163_AddHoaDon_SanPhamBan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
